[package]
name = "pinjector"
version = "0.1.0"
edition = "2021"

[dependencies]
winapi = {version = "0.3.9", features = ["winuser", "processthreadsapi", "errhandlingapi", "handleapi", "memoryapi", "synchapi", "winbase"]}
user32-sys = "0.2.0"